name: update and release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 5'

permissions:
  contents: write

jobs:
  build:
    name: Build ehentai extension
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c

      - name: Set release version
        run: |
          VC=$((10#$(date +%V)))
          LV_MINOR=$(($(date +%Y) - 2026 + 4))
          sed -Ei \
            -e "s/versionCode[[:space:]]*=[[:space:]]*.*/versionCode = $VC/" \
            -e "s/libVersion[[:space:]]*=[[:space:]]*\"[0-9]+\.[0-9]+\"/libVersion = \"1.$LV_MINOR\"/" \
            src/all/ehentai/build.gradle.kts
          sed -Ei \
            -e "s/\"extensionLib\": \"[^\"]*\"/\"extensionLib\": \"1.$LV_MINOR\"/" \
            -e "s/\"versionCode\": \"[^\"]*\"/\"versionCode\": \"$VC\"/" \
            -e "s/\"versionName\": \"[^\"]*\"/\"versionName\": \"1.$LV_MINOR.$VC\"/" \
            -e "s/v[0-9]+\.[0-9]+\.[0-9]+\.apk/v1.$LV_MINOR.$VC.apk/" \
            repo/index.json
          echo "VERSION=v1.${LV_MINOR}.${VC}" >> "$GITHUB_ENV"

      - name: Prepare signing key
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > signingkey.jks

      - name: Update etagdb
        run: |
          bash scripts/update-etagdb.sh

      - name: Build ehentai
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew :src:all:ehentai:assembleRelease

      - name: Bump version
        run: |
          rm -rf ./repo/apk/*
          APK=$(echo src/all/ehentai/build/outputs/apk/release/tachiyomi-all.ehentai*.apk)
          cp "$APK" "./repo/apk/$(basename "${APK/-release/}")"
          cd repo && pip install protobuf && python ../.github/scripts/merge-repo.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: auto build ${{ env.VERSION }} [skip ci]
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Clean up CI files
        if: always()
        run: rm -f signingkey.jks